version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - '/**/*'
    - appspec.yml
    - deploy_scripts/install.sh
    - deploy_scripts/stop.sh
    - deploy_scripts/start.sh
    - deploy_scripts/validate.sh
